#!/usr/bin/env fish

export PATH=$HOME/.nix-profile/bin:$PATH

emacs -Q -nw --load pre-tangle.el --file init.org -f org-babel-tangle -f kill-emacs

if uname -a | grep Darwin
    env NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 home-manager switch
else
    home-manager switch
end

pkill emacs
