#!/usr/bin/env bash

set -ex

cd $(dirname $0)/..

if ! command -v nix-env &> /dev/null
then
    sh <(curl -L https://nixos.org/nix/install) --no-daemon
fi

BOOTSTRAP_SHELL=$SHELL nix-shell -p fish --run ./script/build
