#!/usr/bin/env fish

cd (dirname (status --current-filename))/..

if uname -a | grep Darwin
    set -gx PATH $HOME/.nix-profile/bin $PATH
    set -gx NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM 1
end

emacs -Q -nw --load pre-tangle.el --file init.org -f org-babel-tangle -f kill-emacs

if awesome --check -c awesome/rc.lua
    home-manager switch -f home.nix
end

pkill emacs

source fish/config.fish
