---
- name: System Configuration
  hosts: all

  tasks:
  - name: Add multiverse
    apt_repository:
      repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse

  - name: Add firefox-next ppa
    apt_repository:
      repo: ppa:mozillateam/firefox-next

  - name: Add haxe ppa
    apt_repository:
      repo: ppa:haxe/releases

  - name: Add wine key
    apt_key:
      url: https://dl.winehq.org/wine-builds/winehq.key
      id: D43F640145369C51D786DDEA76F1A20FF987672F

  - name: Add wine repo
    apt_repository:
      repo: deb https://dl.winehq.org/wine-builds/ubuntu {{ansible_distribution_release}} main

  - name: Add mono key
    apt_key: >
      keyserver="hkp://keyserver.ubuntu.com:80"
      id="3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

  - name: Add mono repo
    apt_repository:
      repo: deb https://download.mono-project.com/repo/ubuntu stable-{{ansible_distribution_release}} main

  - name: Add docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

  - name: Add docker ppa
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Update existing apps
    apt:
      cache_valid_time: "{{ (7 * 24 * 60 * 60)|int }}"
      upgrade: "yes"

  - name: Install apps
    apt:
      cache_valid_time: "{{ (7 * 24 * 60 * 60)|int }}"
      name:
        - ansible
        - build-essential
        - cmake
        - curl
        - docker-ce
        - etckeeper
        - fcitx
        - fcitx-mozc
        - firefox
        - fish
        - git
        - libtool-bin
        - mecab
        - mpv
        - nvidia-driver-455
        - steam
        - virt-manager
        - winehq-staging
        - haxe

        # For building hashlink
        - libpng-dev
        - libturbojpeg-dev
        - libvorbis-dev
        - libopenal-dev
        - libsdl2-dev
        - libmbedtls-dev
        - libuv1-dev

        # For building looking-glass
        - binutils-dev
        - libsdl2-dev
        - libsdl2-ttf-dev
        - libspice-protocol-dev
        - libfontconfig1-dev
        - libx11-dev
        - nettle-dev

  - name: Install winetricks
    apt:
      cache_valid_time: "{{ (7 * 24 * 60 * 60)|int }}"
      name:
        - winetricks
    register: winetricks

  - name: Update winetricks
    command: winetricks --self-update
    when: winetricks.changed

  - name: Remove apps
    apt:
      state: absent
      name:
        - muon
        - skanlite
        - vlc
    register: removed_apps

  - name: Autoremove
    apt:
      autoremove: yes
    when: removed_apps.changed

  - name: Install snaps
    community.general.snap:
      name: spectacle

  - name: Set user's shell
    user:
      name: carl
      shell: /usr/bin/fish
      append: yes
      groups: docker

  - name: Add steam game drive
    mount:
      path: /mnt/steam
      src: UUID=4cd6fb31-037c-4bc1-a6e4-a5b206a348d8
      fstype: ext4
      opts: nofail
      state: present

  - name: Update grub config for vfio
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amd_iommu=on vfio-pci.ids=10de:128b,10de:0e0f video=efifb:off"
    register: grub_config

  - name: Update grub
    command: update-grub
    when: grub_config.changed

  - name: Prefer IPv4 DNS
    blockinfile:
      path: /etc/gai.conf
      block: |
        label ::1/128       0
        label ::/0          1
        label 2002::/16     2
        label ::/96         3
        label ::ffff:0:0/96 4
        label fec0::/10     5
        label fc00::/7      6
        label 2001:0::/32   7

        precedence  ::1/128       50
        precedence  ::/0          40
        precedence  2002::/16     30
        precedence ::/96          20
        precedence ::ffff:0:0/96  100

        scopev4 ::ffff:169.254.0.0/112  2
        scopev4 ::ffff:127.0.0.0/104    2
        scopev4 ::ffff:0.0.0.0/96       14

  - name: Add Looking Glass AppArmor exception
    blockinfile:
      path: /etc/apparmor.d/abstractions/libvirt-qemu
      block: |2
          /dev/shm/looking-glass rw,
          /dev/shm/scream rw,
    register: apparmor_config

  - name: Restart AppArmor
    systemd:
      name: apparmor
      state: restarted
    when: apparmor_config.changed

  - name: Set shared mem file permissions
    file:
      path: "{{ item }}"
      state: touch
      owner: carl
      group: kvm
      mode: '0660'
    with_items:
      - /dev/shm/looking-glass
      - /dev/shm/scream

  - name: Turn off DPMS
    copy:
      dest: /usr/share/X11/xorg.conf.d/10-monitor.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes
      content: |
        Section "Extensions"
            Option "DPMS" "Disable"
        EndSection

  - name: Check for nix
    stat:
      path: /nix
    register: nix_store

  - name: Check for nix install script
    stat:
      path: /opt/nix.install.sh
    register: nix_install_sh

  - name: Download nix
    get_url:
      url: https://nixos.org/nix/install
      dest: /opt/nix.install.sh
    when: not nix_store.stat.exists and not nix_install_sh.stat.exists

  - name: Install nix
    script: /opt/nix.install.sh
    become: yes
    become_user: carl
    when: not nix_store.stat.exists
    register: installed_nix
