#!/usr/bin/env bash

cd "$(dirname "$0")"

sudo apt update

sudo apt install ansible

sudo ansible-galaxy collection install community.general

sudo ansible-playbook --connection=local -i ./ansible_hosts --verbose playbook.yml
